require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    # - config/initializers/*
    - node_modules/**/*
    - 'vendor/**/*'
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Exclude:
    - spec/**/*
