version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/www/vulcan/db
  web:
    build: .
    command: bundle exec rails server -p 3030 -b '0.0.0.0'
    volumes:
      - .:/var/www/vulcan
    ports:
      - "3030:3030"
    depends_on:
      - db
